// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemon.UI.Data;

#nullable disable

namespace Pokemon.UI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pokemon.BL.Logic.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonDexNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonDexNum");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("Pokemon.BL.Logic.Pokemon", b =>
                {
                    b.Property<int>("DexNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DexNum"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DexNum");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("Pokemon.BL.Logic.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonDexNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonDexNum");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Pokemon.BL.Logic.Ability", b =>
                {
                    b.HasOne("Pokemon.BL.Logic.Pokemon", null)
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonDexNum");
                });

            modelBuilder.Entity("Pokemon.BL.Logic.Type", b =>
                {
                    b.HasOne("Pokemon.BL.Logic.Pokemon", null)
                        .WithMany("Types")
                        .HasForeignKey("PokemonDexNum");
                });

            modelBuilder.Entity("Pokemon.BL.Logic.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
